spring:
  application:
    name: config-server
  rabbitmq:
    host: 172.17.132.96
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quantumCom/test
          search-paths: config-repo   #多个的话用拼音隔开
          username:
          password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9898
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"


