spring:
  application:
    name: client1
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    
feign:
  hystrix:
    enabled: true
server:
  port: 8762
value1: helloNew
management:
  security:
    enabled: false
  server:
    port: 8762
  endpoints:
    web:
#      base-path: / #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"  #打开全部请求端点
#        include: refresh,health,info #打开部分
