spring:
  application:
    name: client2
  rabbitmq:
    host: 172.17.132.96
    port: 5672
    username: admin
    password: admin
feign:
  hystrix:
    enabled: true
server:
  port: 8763
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
value1: hello
