spring:
  application:
    name: client2
feign:
  hystrix:
    enabled: true
server:
  port: 8763
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
value1: hello
