spring:
  application:
    name: gateway
  cloud:
    gateway:
#      routes:
#        - id: fsh-house
#          uri: lb://fsh-house
#          predicates:
#            - Path=/house/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 8888
